server:
  port: 8000 # 指定启动端口
spring:
  cloud:
    gateway:
#      httpclient:
#        pool:
#            type: fixed
#            max-connections: 48
      routes:
        - id: auth
          uri: lb://eaqb-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  data:
    redis:
      database: 5 # Redis 数据库索引（默认为 0）
      host: ${SERVER_IP} # Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
      password: qwe123!@# # Redis 服务器连接密码（默认为空）
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true
# 关键：配置网关自身的 Actuator 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*" #health,info,metrics  # 暴露网关自身的 /actuator/health 接口
      base-path: /actuator  # 接口基础路径（默认就是 /actuator，可省略）
  endpoint:
    health:
      show-details: always  # 显示详细健康信息（如网关的路由状态、连接池等）